In [14]:
import numpy as np

***
* np.array([array sequence])

In [15]:
X = np.array([1, 2, 3, 4, 5])
print(X)

[1 2 3 4 5]


***
* np.zeros(shape)

In [16]:
X = np.zeros((3,4))
print(X)
print(X.dtype)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
float64


***
* np.ones(shape)

In [17]:
X = np.ones((3,2), dtype=str)
print(X)

[['1' '1']
 ['1' '1']
 ['1' '1']]


***
* np.full(shape, constant value)

In [18]:
X = np.full((4,3), 5)
print(X)
print(X.dtype)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
int32


***
* np.eye(N)
>*returns an 'identity matrix', an NxN matrix with 1's along main diagonal and 0's elsewhere*

In [19]:
X = np.eye(5, dtype=int)
print(X)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


***
* np.diag(1d array)

In [20]:
X = np.diag([10, 20, 30, 40, 50])
print(X)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


***
* np.arange(start, stop, step)
>*Note that stop is EXclusive (n-1)*

In [21]:
X = np.arange(5)
print(X)

[0 1 2 3 4]


In [22]:
X = np.arange(0, 6, 2, dtype=float)
print(X)

[ 0.  2.  4.]


***
* np.linspace(start, stop, N)
>*Note that stop is INclusive unless*  endpoint=False  
*Also note that*  N=50  *by default*

In [23]:
X = np.linspace(0, 25, 10)
print(X)

[  0.           2.77777778   5.55555556   8.33333333  11.11111111
  13.88888889  16.66666667  19.44444444  22.22222222  25.        ]


In [24]:
X = np.linspace(0, 25, 10, endpoint=False)
print(X)

[  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5]


In [25]:
X = np.linspace(0, 10)
print(X)

[  0.           0.20408163   0.40816327   0.6122449    0.81632653
   1.02040816   1.2244898    1.42857143   1.63265306   1.83673469
   2.04081633   2.24489796   2.44897959   2.65306122   2.85714286
   3.06122449   3.26530612   3.46938776   3.67346939   3.87755102
   4.08163265   4.28571429   4.48979592   4.69387755   4.89795918
   5.10204082   5.30612245   5.51020408   5.71428571   5.91836735
   6.12244898   6.32653061   6.53061224   6.73469388   6.93877551
   7.14285714   7.34693878   7.55102041   7.75510204   7.95918367
   8.16326531   8.36734694   8.57142857   8.7755102    8.97959184
   9.18367347   9.3877551    9.59183673   9.79591837  10.        ]


***
* np.reshape(ndarray, shape)
>*Note that the number of elements in* ndarray *must be divisible into* shape

In [26]:
X = np.arange(25)
X = np.reshape(X, (4,5))
print(X)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [126]:
X = np.arange(20)
print(X)
print('\nafter .reshape:')
X = np.reshape(X, (4,5))
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after .reshape:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


***
* Some Numpy functions can also be used as methods.
>*Note that when using reshape as a method the array does not get passed as an arg.*

In [127]:
X = np.arange(10).reshape((2, 5))
print(X)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5,2)
print(X)

[[  0.   5.]
 [ 10.  15.]
 [ 20.  25.]
 [ 30.  35.]
 [ 40.  45.]]


***
*Random matrice generation is often used in Machine Learning design*  
  
* np.random.random((shape))
>*The first .random accesses the module, the second accesses the function within the module.*


In [30]:
X = np.random.random((3, 3))
print(X)

[[ 0.83998986  0.6902607   0.54554311]
 [ 0.38654949  0.44152518  0.65922539]
 [ 0.23599152  0.88906054  0.01891066]]


***
* np.random.randint(lowerbound, upperbound, (shape))

In [128]:
X = np.random.randint(4, 15, (3, 2))
print(X)

[[12 11]
 [13  5]
 [ 4 11]]


***
* np.random.normal(mean, st.deviation, (shape))

In [32]:
X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

[[-0.00196997  0.0409898   0.02499055 ..., -0.03179525 -0.1402223
   0.01910703]
 [-0.24797291 -0.14724266 -0.08901773 ..., -0.06477495 -0.00420239
   0.08245396]
 [-0.12206975  0.00290242  0.01018584 ..., -0.03280217  0.02678685
   0.1609856 ]
 ..., 
 [-0.17929758  0.10788027 -0.06834597 ..., -0.1200289  -0.03066488
  -0.02681263]
 [ 0.14371202  0.11775155 -0.07463737 ..., -0.10565031  0.03909733
  -0.15439013]
 [-0.03290552  0.02916288 -0.04208316 ..., -0.039172   -0.11553026
   0.01001101]]


In [33]:
print('mean:', X.mean())
print('std:', X.std())
print('max:', X.max())
print('min:', X.min())
print('# positive:', (X > 0).sum())
print('# negative:', (X < 0).sum())

mean: 0.000102676498708
std: 0.100106910057
max: 0.497801362809
min: -0.468850023538
# positive: 500421
# negative: 499579


***
### Accessing/Deleting/Inserting Elements into ndarrays

In [129]:
rank_1_array = np.array([1,2,3,4,5])
rank_2_array = np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [125]:
X = rank_1_array.copy()
print(X)
print(X[0])
print(X[1])
print(X[-1])
print(X[-5])

[ 1  2  3 20  5]
1
2
5
1


In [36]:
X[3] = 20
print(X)

[ 1  2  3 20  5]


In [130]:
X = rank_2_array.copy()
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* ndarray[row, column]

In [38]:
print(X[0,0])
print(X[0,1])
print(X[2,2])

1
2
9


In [39]:
X[0,0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


***
* np.delete(ndarray, elements, axis)
>*For rank-1 arrays the axis is not required. For rank-2 arrays,* axis=0 *selects ROWS and* axis=1 *selects COLUMNS.*

In [131]:
print('1d array:')
X = rank_1_array.copy()
print(X)
X = np.delete(X, [0,4])
print(X)

1d array:
[1 2 3 4 5]
[2 3 4]


In [132]:
print('2d array:')
X = rank_2_array.copy()
print(X)
print('Delete first row (line 5):')
Y = np.delete(X, 0, axis=0)
print(Y)
print('Delete first column (line 8):')
Z = np.delete(X, 0, axis=1)
print(Z)
print('Delete first and last column (line 11):')
X = np.delete(X, [0,2], axis=1)
print(X)

2d array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Delete first row (line 5):
[[4 5 6]
 [7 8 9]]
Delete first column (line 8):
[[2 3]
 [5 6]
 [8 9]]
Delete first and last column (line 11):
[[2]
 [5]
 [8]]


***
* np.append(ndarray, elements, axis)
>*For rank-1 arrays the axis is not required. For rank-2 arrays,* axis=0 *selects ROWS and* axis=1 *selects COLUMNS.*  
*Note that the rows/column being appended must have the corret shape.*

In [133]:
print('1d array:')
X = rank_1_array.copy()
print(X)
print('Append int 6 to array (line 5):')
X = np.append(X, 6)
print(X)
print("Append int's 7 & 8 to array (line 8)")
X = np.append(X, [7,8])
print(X)

1d array:
[1 2 3 4 5]
Append int 6 to array (line 5):
[1 2 3 4 5 6]
Append int's 7 & 8 to array (line 8)
[1 2 3 4 5 6 7 8]


In [134]:
print('2d array:')
X = np.delete(rank_2_array, 2, axis=0)
print(X)
print('Append new row containing [7,8,9] (line 5):')
X = np.append(X, [[7,8,9]], axis=0)
print(X)
print('Append new column containing [9], [10], [11] (line 8):')
X = np.append(X, [[9],[10],[11]], axis=1)
print(X)

2d array:
[[1 2 3]
 [4 5 6]]
Append new row containing [7,8,9] (line 5):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Append new column containing [9], [10], [11] (line 8):
[[ 1  2  3  9]
 [ 4  5  6 10]
 [ 7  8  9 11]]


***
* np.insert(ndarray, index, elements, axis)
>*For rank-1 arrays the axis is not required. For rank-2 arrays, axis=0 selects ROWS and axis=1 selects COLUMNS.*  
*Note that the rows/column being appended must have the corret shape.*


In [135]:
X = rank_1_array.copy()
print(X)
X = np.insert(X, 2, [3,4])
print(X)

[1 2 3 4 5]
[1 2 3 4 3 4 5]


In [136]:
X = rank_2_array.copy()
print(X)
print('Insert a row between first and last row (line 4):')
X = np.insert(X, 1,[4,5,6], axis=0)
print(X)
X = rank_2_array.copy()
print("Insert a column full of 5's between first and second column (line 8):")
X = np.insert(X, 1, 5, axis=1)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Insert a row between first and last row (line 4):
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
Insert a column full of 5's between first and second column (line 8):
[[1 5 2 3]
 [4 5 5 6]
 [7 5 8 9]]


***
* np.vstack(stack, ndarray)
>*Note that the item being stacked must have the correct shape. See how the hstack example uses .reshape to transform the appended array into a suitable shape.*

In [46]:
X = np.array([1,2])
print('Rank 1 array:')
print(X)
Y = np.array([[3,4],[5,6]])
print('Rank 2 array:')
print(Y)
Z = np.vstack((X, Y))
print('Stacked with vstack: (line 7):')
print(Z)
print('Stacked with hstack: (line 9):')
Z = np.hstack((Y, X.reshape(2,1)))
print(Z)

Rank 1 array:
[1 2]
Rank 2 array:
[[3 4]
 [5 6]]
Stacked with vstack: (line 7):
[[1 2]
 [3 4]
 [5 6]]
Stacked with hstack: (line 9):
[[3 4 1]
 [5 6 2]]


***
### Slicing  
* ndarray[row_start:row_end, column_start:column_end]
>*WARNING: assigning a new variable name to a slice of a ndarray only creates a "view" of that ndarray. If the variable assigned to the slice is changed, the original ndarray will be changed as well. Example follows below (issue can be avoided by using .copy function).*

In [67]:
x = np.arange(1, 21).reshape(4,5)
print(x)
print('\nAfter slice [1:4, 2:5]:')
my_slice = x[1:4, 2:5]
print(my_slice)
print ('\nAfter slice [2:, 1:]')
my_slice = x[2:, 1:]
print(my_slice)
print('\nAfter slice [:, 2] (notice it returns rank 1 array):')
my_slice = x[:, 2]
print(my_slice)
my_slice = x[:, 2:3]
print('\nAfter slice [:, 2:3] (notice it returns rank 2 array):')
print(my_slice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

After slice [1:4, 2:5]:
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]

After slice [2:, 1:]
[[12 13 14 15]
 [17 18 19 20]]

After slice [:, 2] (notice it returns rank 1 array):
[ 3  8 13 18]

After slice [:, 2:3] (notice it returns rank 2 array):
[[ 3]
 [ 8]
 [13]
 [18]]


* example of "view" variable assignment:

In [87]:
x = np.arange(1, 21).reshape(4,5)
print(x)
print('\nSlice: ')
my_slice = x[1:, 2:]
print(my_slice)
print('\nLast entry in slice changed to 55 (line 7):')
my_slice[2, 2] = 55
print(my_slice)
print('\nOriginal ndarray changed too:')
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Slice: 
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]

Last entry in slice changed to 55 (line 7):
[[ 8  9 10]
 [13 14 15]
 [18 19 55]]

Original ndarray changed too:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 55]]


***
* np.copy()
>*Avoids above problem.

In [95]:
x = np.arange(1, 21).reshape(4,5)
my_slice = x[1:, 2:].copy()
my_slice[2, 2] = 55
print('Changed slice:')
print(my_slice)
print('\nUnchanged original:')
print(x)

Changed slice:
[[ 8  9 10]
 [13 14 15]
 [18 19 55]]

Unchanged original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


***
* Indices: use one ndarray to make slices, select, or change elements in another ndarray.

In [101]:
x = np.arange(20).reshape(4,5)
print(x)
indices = np.array([1,3])
print('\nIndices: ', indices)
z = x[indices, :]
print('\nSelection from rows using indices:')
print(z)
z = x[:, indices]
print('\nSelection from columns using indices:')
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Indices:  [1 3]

Selection from rows using indices:
[[ 5  6  7  8  9]
 [15 16 17 18 19]]

Selection from columns using indices:
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


***
* np.diag(ndarray, k=N)
>k=N *is the position relative to the main diagonal with positive values selecting to the right and negative values selecting to the left.*

In [112]:
x = np.arange(25).reshape(5,5)
print(x,'\n')
print('elements in main diag: ', np.diag(x))
print('\nelements above main diag (k=1):', np.diag(x, k=1))
print('\nelements below main diag (k=-1):', np.diag(x, k=-1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

elements in main diag:  [ 0  6 12 18 24]

elements above main diag (k=1): [ 1  7 13 19]

elements below main diag (k=-1): [ 5 11 17 23]


***
* np.unique(ndarray)

In [114]:
x = np.array([[1,2,3],[5,2,8],[1,2,3]])
print('Unique elements are:', np.unique(x))

Unique elements are: [1 2 3 5 8]


***
### Boolean Indexing

In [123]:
x = np.arange(25).reshape(5, 5)
print(x,'\n')
print('Elements in x greater than 10:', x[x > 10])
print('Elements in x less than or equal to 7:', x[x <= 7])
print('Elements in x between 10 and 17:', x[(x > 10) & (x < 17)])

print('\nReassigning values between 10 and 17 to -1:')
x[(x > 10) & (x < 17)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Elements in x greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Elements in x less than or equal to 7: [0 1 2 3 4 5 6 7]
Elements in x between 10 and 17: [11 12 13 14 15 16]

Reassigning values between 10 and 17 to -1:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


***
Set Operations:
* np.intersect1d(first_rank1, second_rank2)
* np.setdiff1d(first_rank1, second_rank2)
* np.union1d(first_rank1, second_rank2)

In [144]:
x = rank_1_array.copy()
y = np.array([6,7,2,8,4])
print('x:',x)
print('y:',y)
print('Elements in both x and y:', np.intersect1d(x,y))
print('Elements in x that are not in y:', np.setdiff1d(x,y))
print('All elements of both x and y:', np.union1d(x,y))

x: [1 2 3 4 5]
y: [6 7 2 8 4]
Elements in both x and y: [2 4]
Elements in x that are not in y: [1 3 5]
All elements of both x and y: [1 2 3 4 5 6 7 8]
